name: Build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
    build:
      name: Build
      runs-on: macos-12
      steps:
        - name: Build
          run: swift build
        - name: Run tests
          run: swift test
